name: labo_final
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_login: ^4.2.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  provider: ^6.0.5
  firebase_ui_auth: ^1.7.0
  cupertino_icons: ^1.0.2
  flutter_animated_splash: ^0.0.10
  animated_splash_screen: ^1.3.0
  firebase_storage: ^11.2.6
  image_picker: ^1.0.4
  email_validator: ^2.1.17
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/students.png"

flutter:
  uses-material-design: true

  assets:
    - images/students.png
    - images/default_image.png
    - images/splash.jpg

